/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InheritancePackage;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;

/**
 *
 * @author Muhammad Faheem
 */
public class EmailingEmployee extends javax.swing.JFrame {
       LoginPage LP = new LoginPage();
       boolean found = false;
       
public void CheckingEmail(String x){

         String fileName = LP.fileName;

        try {
            FileReader reader = new FileReader(fileName);
            BufferedReader br = new BufferedReader(reader);
            String line;

            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                
                if (parts[2].toLowerCase().equals(EmailField.getText().trim().toLowerCase())){                
                  found = true;
        }

            }
            reader.close();
            br.close();
        }    
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
    }
    
    public EmailingEmployee() {
        initComponents();
        UsernameLabel.setText((String) LP.fileName);
        this.setOpacity(0.95f);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JPanel();
        SignOutPanel = new javax.swing.JPanel();
        SignOutLabel = new javax.swing.JLabel();
        EditPanel = new javax.swing.JPanel();
        EditLabel = new javax.swing.JLabel();
        RemovePanel = new javax.swing.JPanel();
        RemoveLabel = new javax.swing.JLabel();
        ViewPanel = new javax.swing.JPanel();
        ViewLabel = new javax.swing.JLabel();
        AddPanel = new javax.swing.JPanel();
        AddLabel = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        MenuLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        eE = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Emailing = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        SubjectLabel = new javax.swing.JLabel();
        SubjectField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        MessageLabel = new javax.swing.JLabel();
        ToolPanel1 = new javax.swing.JPanel();
        ToolLabel1 = new javax.swing.JLabel();
        Email = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Message = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Find = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        ExitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Information and Mangement System");
        setMinimumSize(new java.awt.Dimension(560, 670));
        setUndecorated(true);
        getContentPane().setLayout(null);

        MenuBar.setBackground(new java.awt.Color(0, 102, 153));
        MenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignOutPanel.setBackground(new java.awt.Color(0, 102, 153));
        SignOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignOutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignOutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignOutPanelMouseExited(evt);
            }
        });
        SignOutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignOut.png"))); // NOI18N
        SignOutPanel.add(SignOutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(SignOutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 50, 30));

        EditPanel.setBackground(new java.awt.Color(0, 102, 153));
        EditPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditPanelMouseExited(evt);
            }
        });
        EditPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit_1.png"))); // NOI18N
        EditPanel.add(EditLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(EditPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 50, 30));

        RemovePanel.setBackground(new java.awt.Color(0, 102, 153));
        RemovePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemovePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RemovePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RemovePanelMouseExited(evt);
            }
        });
        RemovePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RemoveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Remove.png"))); // NOI18N
        RemovePanel.add(RemoveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(RemovePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 50, 30));

        ViewPanel.setBackground(new java.awt.Color(0, 102, 153));
        ViewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewPanelMouseExited(evt);
            }
        });
        ViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View.png"))); // NOI18N
        ViewPanel.add(ViewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(ViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 50, 30));

        AddPanel.setBackground(new java.awt.Color(0, 102, 153));
        AddPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddPanelMouseExited(evt);
            }
        });
        AddPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        AddPanel.add(AddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(AddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 30));

        MenuPanel.setBackground(new java.awt.Color(0, 102, 153));
        MenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuPanelMouseExited(evt);
            }
        });
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu.png"))); // NOI18N
        MenuPanel.add(MenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 50, 30));

        getContentPane().add(MenuBar);
        MenuBar.setBounds(0, 0, 50, 1000);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eE.setBackground(new java.awt.Color(255, 255, 255));
        eE.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        eE.setForeground(new java.awt.Color(51, 52, 54));
        eE.setText("Employee Email");
        jPanel1.add(eE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        EmailField.setBackground(new java.awt.Color(0, 0, 0));
        EmailField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        EmailField.setForeground(new java.awt.Color(255, 153, 0));
        EmailField.setBorder(null);
        EmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFieldFocusLost(evt);
            }
        });
        jPanel1.add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 360, 20));

        jSeparator2.setMaximumSize(null);
        jSeparator2.setMinimumSize(null);
        jSeparator2.setPreferredSize(null);
        jSeparator2.setRequestFocusEnabled(false);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 360, 10));

        Emailing.setBackground(new java.awt.Color(0, 0, 0));
        Emailing.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Emailing.setFocusTraversalPolicyProvider(true);
        Emailing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmailingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmailingMouseExited(evt);
            }
        });
        Emailing.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/send email.png"))); // NOI18N
        Emailing.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        EmailLabel.setBackground(new java.awt.Color(255, 255, 255));
        EmailLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Email");
        Emailing.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, -1));

        jPanel1.add(Emailing, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 90, 90));

        SubjectLabel.setBackground(new java.awt.Color(255, 255, 255));
        SubjectLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        SubjectLabel.setForeground(new java.awt.Color(51, 52, 54));
        SubjectLabel.setText("Subject");
        jPanel1.add(SubjectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, -1));

        SubjectField.setBackground(new java.awt.Color(0, 0, 0));
        SubjectField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SubjectField.setForeground(new java.awt.Color(255, 153, 0));
        SubjectField.setBorder(null);
        SubjectField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SubjectFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SubjectFieldFocusLost(evt);
            }
        });
        jPanel1.add(SubjectField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 430, 20));

        jSeparator3.setMaximumSize(null);
        jSeparator3.setMinimumSize(null);
        jSeparator3.setPreferredSize(null);
        jSeparator3.setRequestFocusEnabled(false);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 430, 20));

        MessageLabel.setBackground(new java.awt.Color(255, 255, 255));
        MessageLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        MessageLabel.setForeground(new java.awt.Color(51, 52, 54));
        MessageLabel.setText("Message");
        jPanel1.add(MessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        ToolPanel1.setBackground(new java.awt.Color(0, 0, 0));
        ToolPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ToolPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ToolPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ToolPanel1MouseExited(evt);
            }
        });
        ToolPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToolLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ToolLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ToolLabel1.setText("Edit Employee in the System");
        ToolPanel1.add(ToolLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jPanel1.add(ToolPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 50));

        Email.setBackground(new java.awt.Color(0, 0, 0));
        Email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Email.setFocusTraversalPolicyProvider(true);
        Email.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        Message.setBackground(new java.awt.Color(0, 0, 0));
        Message.setColumns(20);
        Message.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Message.setForeground(new java.awt.Color(255, 153, 0));
        Message.setLineWrap(true);
        Message.setRows(5);
        Message.setBorder(null);
        Message.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Message.setMargin(new java.awt.Insets(5, 5, 5, 5));
        Message.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MessageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MessageFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(Message);

        Email.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 310));

        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 490, 330));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 50, 920, 620);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(100, 40, 210, 10);

        Find.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Find.setForeground(new java.awt.Color(255, 153, 0));
        Find.setBorder(null);
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });
        Find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FindKeyPressed(evt);
            }
        });
        jPanel3.add(Find);
        Find.setBounds(100, 10, 210, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(60, 10, 32, 30);

        UsernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Icon.png"))); // NOI18N
        UsernameLabel.setText("Username");
        jPanel3.add(UsernameLabel);
        UsernameLabel.setBounds(410, 0, 100, 40);

        ExitPanel.setBackground(new java.awt.Color(255, 255, 255));
        ExitPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ExitPanel.setMaximumSize(new java.awt.Dimension(32, 32));
        ExitPanel.setMinimumSize(new java.awt.Dimension(32, 32));
        ExitPanel.setPreferredSize(new java.awt.Dimension(32, 32));
        ExitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitPanelMouseExited(evt);
            }
        });
        ExitPanel.setLayout(new java.awt.GridLayout(1, 0));

        ExitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit2.png"))); // NOI18N
        ExitPanel.add(ExitLabel);

        jPanel3.add(ExitPanel);
        ExitPanel.setBounds(520, 0, 32, 32);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 980, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int xMouse, yMouse;
    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y= evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse); 
    }//GEN-LAST:event_jPanel3MouseDragged

    private void MenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_MenuPanelMouseClicked

    private void MenuPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPanelMouseEntered
        MenuPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_MenuPanelMouseEntered

    private void MenuPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPanelMouseExited
        // TODO add your handling code here:
        MenuPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_MenuPanelMouseExited

    private void AddPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AddEmployee().setVisible(true);        
    }//GEN-LAST:event_AddPanelMouseClicked

    private void AddPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseEntered
        // TODO add your handling code here:
        AddPanel.setBackground(new Color(255,153,0));

    }//GEN-LAST:event_AddPanelMouseEntered

    private void AddPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseExited
        // TODO add your handling code here:
        AddPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_AddPanelMouseExited

    private void RemovePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemovePanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new RemoveEmployee().setVisible(true);
    }//GEN-LAST:event_RemovePanelMouseClicked

    private void RemovePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemovePanelMouseEntered
        // TODO add your handling code here:
       RemovePanel.setBackground(new Color(255,153,0));

    }//GEN-LAST:event_RemovePanelMouseEntered

    private void RemovePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemovePanelMouseExited
        // TODO add your handling code here:
       RemovePanel.setBackground(new Color(0,102,153));

    }//GEN-LAST:event_RemovePanelMouseExited

    private void EditPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new EmailingEmployee().setVisible(true);
    }//GEN-LAST:event_EditPanelMouseClicked

    private void EditPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPanelMouseEntered
        // TODO add your handling code here:
       EditPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_EditPanelMouseEntered

    private void EditPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPanelMouseExited
        // TODO add your handling code here:
       EditPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_EditPanelMouseExited

    private void ViewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPanelMouseClicked
        this.dispose();
        new DisplaySystem().setVisible(true);        
    }//GEN-LAST:event_ViewPanelMouseClicked

    private void ViewPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPanelMouseEntered
        // TODO add your handling code here:
       ViewPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_ViewPanelMouseEntered

    private void ViewPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPanelMouseExited
       ViewPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_ViewPanelMouseExited

    private void SignOutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutPanelMouseClicked
       new LoginPage().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_SignOutPanelMouseClicked

    private void SignOutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutPanelMouseEntered
       SignOutPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_SignOutPanelMouseEntered

    private void SignOutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutPanelMouseExited
       SignOutPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_SignOutPanelMouseExited

    private void ExitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitPanelMouseClicked

    private void ExitPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseEntered
        ExitLabel.setForeground(Color.WHITE);
        ExitPanel.setBackground(new Color(255, 255, 255));
        ExitPanel.setBorder(new LineBorder(new Color(255, 153, 0), 1, true));
    }//GEN-LAST:event_ExitPanelMouseEntered

    private void ExitPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseExited
        ExitLabel.setForeground(new Color(255, 153, 0));
        ExitPanel.setBackground(new Color(0, 102, 153));
        ExitPanel.setBorder(new LineBorder(Color.WHITE, 0, true));
    }//GEN-LAST:event_ExitPanelMouseExited

    private void EmailingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailingMouseExited
        // TODO add your handling code here:
        EmailLabel.setForeground(Color.white);
        Emailing.setBackground(Color.BLACK);
        Emailing.setBorder(new LineBorder(Color.WHITE,1,true));
    }//GEN-LAST:event_EmailingMouseExited

    private void EmailingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailingMouseEntered
        // TODO add your handling code here:
        EmailLabel.setForeground(Color.WHITE);
        Emailing.setBackground(new Color(255,153,0));
        Emailing.setBorder(new LineBorder(new Color(255,153,0),1,true));
    }//GEN-LAST:event_EmailingMouseEntered

    private void EmailingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailingMouseClicked
        CheckingEmail(EmailField.getText().trim());
        if (EmailField.getText().isEmpty()||SubjectField.getText().isEmpty()||Message.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all the fields!");
        }
        if (found == true){
        Multithread sending = new Multithread(EmailField.getText().trim(),SubjectField.getText().trim(),Message.getText()); 
        Thread sent = new Thread(sending);
        sent.start();
        found = false;
        EmailField.setText(null);
        SubjectField.setText(null);
        Message.setText(null);
        new Menu().setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null, "Email sent!");
        }
        else{
           JOptionPane.showMessageDialog(null, "Email is not in the database!");
        }
        
    }//GEN-LAST:event_EmailingMouseClicked

    private void FindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FindKeyPressed
        DisplaySystem DS = new DisplaySystem();
          if (evt.getKeyCode()==KeyEvent.VK_ENTER){
          DS.Search(Find.getText().trim());
         }    }//GEN-LAST:event_FindKeyPressed

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindActionPerformed

    private void ToolPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ToolPanel1MouseEntered

    private void ToolPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolPanel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ToolPanel1MouseExited

    private void SubjectFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SubjectFieldFocusGained
        jSeparator2.setBackground(Color.yellow);
        SubjectLabel.setForeground(new Color(53,113,177));
    }//GEN-LAST:event_SubjectFieldFocusGained

    private void SubjectFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SubjectFieldFocusLost
        SubjectLabel.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_SubjectFieldFocusLost

    private void EmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusGained
        eE.setForeground(new Color(53,113,177));    }//GEN-LAST:event_EmailFieldFocusGained

    private void EmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusLost
        eE.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_EmailFieldFocusLost

    private void MessageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MessageFocusGained
    MessageLabel.setForeground(new Color(53,113,177));    }//GEN-LAST:event_MessageFocusGained

    private void MessageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MessageFocusLost
        MessageLabel.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_MessageFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailingEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailingEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailingEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailingEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailingEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLabel;
    private javax.swing.JPanel AddPanel;
    private javax.swing.JLabel EditLabel;
    private javax.swing.JPanel EditPanel;
    private javax.swing.JPanel Email;
    public static javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel Emailing;
    private javax.swing.JLabel ExitLabel;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JTextField Find;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JTextArea Message;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JLabel RemoveLabel;
    private javax.swing.JPanel RemovePanel;
    private javax.swing.JLabel SignOutLabel;
    private javax.swing.JPanel SignOutPanel;
    private javax.swing.JTextField SubjectField;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JLabel ToolLabel1;
    private javax.swing.JPanel ToolPanel1;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel ViewLabel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JLabel eE;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
