/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InheritancePackage;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Muhammad Faheem
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     *
     */
    public static String fileName;

    boolean found = false;
    boolean found2 = false;
    boolean found3= false;
    String passcode;
    String usercode;
    public void LoginCheck(){

         String fileName = "LoginInfo.txt";

       try {
           found = false;
           found2 = false;
           found3 = false;
            FileReader reader = new FileReader(fileName);
            BufferedReader br = new BufferedReader(reader); 

            String line;
           if (Username.getText().isEmpty()|| String.valueOf(Password.getPassword()).isEmpty()){
        JOptionPane.showMessageDialog(null,"FILL IN ALL FIELDS!");
        found2 = true;
        }
           else{
            while ((line = br.readLine()) != null) {
               String[] parts = line.split(",");
               passcode = parts[1];
                if (parts[0].toLowerCase().equals(Username.getText().trim().toLowerCase())&&passcode.equals(String.valueOf(Password.getPassword()))){
                    found =  true;
            }
            else if (parts[0].toLowerCase().equals(Username.getText().trim().toLowerCase())&&!passcode.equals(String.valueOf(Password.getPassword()))){
                JOptionPane.showMessageDialog(null,"Username or Passwrod is Incorrect!");    
                found3 = true;  
           }
            }
           }
           if (found == false&&found2==false&&found3==false){
            JOptionPane.showMessageDialog(null,"Account Does Not Exist!");
            Username.setText("");
            Password.setText("");  
            found2=false;
            }   
          
        reader.close();
        br.close();
       }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage()); ;
        }
    }    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        this.setOpacity(0.8f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        ExitLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Password = new javax.swing.JPasswordField();
        SignPanel = new javax.swing.JPanel();
        SignLabel = new javax.swing.JLabel();
        BackPanel = new javax.swing.JPanel();
        BackLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(408, 290));
        setMinimumSize(new java.awt.Dimension(408, 290));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(408, 290));
        setResizable(false);

        Main.setBackground(new java.awt.Color(0, 0, 0));
        Main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 6, true));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/person-male.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 86));

        ExitPanel.setBackground(new java.awt.Color(0, 102, 153));
        ExitPanel.setPreferredSize(new java.awt.Dimension(25, 25));
        ExitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitPanelMouseExited(evt);
            }
        });

        ExitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit2.png"))); // NOI18N

        javax.swing.GroupLayout ExitPanelLayout = new javax.swing.GroupLayout(ExitPanel);
        ExitPanel.setLayout(ExitPanelLayout);
        ExitPanelLayout.setHorizontalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ExitPanelLayout.setVerticalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(ExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 0, -1, -1));

        Main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 396, 100));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 52, 54));
        jLabel2.setText("User Name");
        Main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 125, -1, -1));

        Username.setBackground(new java.awt.Color(0, 0, 0));
        Username.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 153, 0));
        Username.setBorder(null);
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsernameKeyPressed(evt);
            }
        });
        Main.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 125, 199, -1));
        Main.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 147, 199, 10));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 52, 54));
        jLabel3.setText("Password");
        Main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        Main.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 192, 199, 10));

        Password.setBackground(new java.awt.Color(0, 0, 0));
        Password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 153, 0));
        Password.setBorder(null);
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });
        Main.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 202, -1));

        SignPanel.setBackground(new java.awt.Color(0, 0, 0));
        SignPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        SignPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignPanelMouseExited(evt);
            }
        });

        SignLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SignLabel.setForeground(new java.awt.Color(255, 153, 0));
        SignLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignLabel.setText("Sign In");

        javax.swing.GroupLayout SignPanelLayout = new javax.swing.GroupLayout(SignPanel);
        SignPanel.setLayout(SignPanelLayout);
        SignPanelLayout.setHorizontalGroup(
            SignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        SignPanelLayout.setVerticalGroup(
            SignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Main.add(SignPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        BackPanel.setBackground(new java.awt.Color(0, 0, 0));
        BackPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        BackPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackPanelMouseExited(evt);
            }
        });

        BackLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BackLabel.setForeground(new java.awt.Color(255, 153, 0));
        BackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackLabel.setText("Sign Up");

        javax.swing.GroupLayout BackPanelLayout = new javax.swing.GroupLayout(BackPanel);
        BackPanel.setLayout(BackPanelLayout);
        BackPanelLayout.setHorizontalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BackLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        BackPanelLayout.setVerticalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        Main.add(BackPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignPanelMouseEntered
        SignLabel.setForeground(Color.WHITE);
        SignPanel.setBackground(new Color(255,153,0));
        SignPanel.setBorder(new LineBorder(new Color(255,153,0),1,true));
    }//GEN-LAST:event_SignPanelMouseEntered

    private void SignPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignPanelMouseClicked
        // TODO add your handling code here:
        fileName = Username.getText().trim();
        LoginCheck();
         if (found == true){
             new Menu().setVisible(true);
            LoginPage.this.dispose();
            Password.setText("");
            Username.setText("");
            found = false;

         }

    }//GEN-LAST:event_SignPanelMouseClicked

    private void SignPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignPanelMouseExited
        // TODO add your handling code here:
        SignLabel.setForeground(new Color(255,153,0));
        SignPanel.setBackground(Color.BLACK);
        SignPanel.setBorder(new LineBorder(Color.WHITE,1,true));
    }//GEN-LAST:event_SignPanelMouseExited

    private void BackPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPanelMouseEntered
        BackLabel.setForeground(Color.WHITE);
        BackPanel.setBackground(new Color(255,153,0));
        BackPanel.setBorder(new LineBorder(new Color(255,153,0),1,true));
    }//GEN-LAST:event_BackPanelMouseEntered

    private void BackPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPanelMouseExited
        BackLabel.setForeground(new Color(255,153,0));
        BackPanel.setBackground(Color.BLACK);
        BackPanel.setBorder(new LineBorder(Color.WHITE,1,true));    
          }//GEN-LAST:event_BackPanelMouseExited

    private void BackPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPanelMouseClicked
        LoginPage.this.dispose();
        new RegisterPage().setVisible(true);    }//GEN-LAST:event_BackPanelMouseClicked

    private void ExitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitPanelMouseClicked

    private void ExitPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseEntered
        ExitLabel.setForeground(Color.WHITE);
        ExitPanel.setBackground(new Color(255,255,255));
        ExitPanel.setBorder(new LineBorder(new Color(255,153,0),1,true));
    }//GEN-LAST:event_ExitPanelMouseEntered

    private void ExitPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseExited
        // TODO add your handling code here:
        ExitLabel.setForeground(new Color(255,153,0));
        ExitPanel.setBackground(new Color(0,102,153));
        ExitPanel.setBorder(new LineBorder(Color.WHITE,0,true));
    }//GEN-LAST:event_ExitPanelMouseExited

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        jLabel2.setForeground(new Color(53,113,177));                                        
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        jLabel2.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_UsernameFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        jLabel3.setForeground(new Color(53,113,177));    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        jLabel3.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_PasswordFocusLost

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        
        fileName = Username.getText().trim();
        LoginCheck();
         if (found == true){
             new Menu().setVisible(true);
            LoginPage.this.dispose();
            Password.setText("");
            Username.setText("");
            found = false;
         }   
         }    
    }//GEN-LAST:event_PasswordKeyPressed

    private void UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        
        fileName = Username.getText().trim();
        LoginCheck();
         if (found == true){
             new Menu().setVisible(true);
            LoginPage.this.dispose();
            Password.setText("");
            Username.setText("");
            found = false;
         }   
         }
     }//GEN-LAST:event_UsernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLabel;
    private javax.swing.JPanel BackPanel;
    private javax.swing.JLabel ExitLabel;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JPanel Main;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel SignLabel;
    private javax.swing.JPanel SignPanel;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
