/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InheritancePackage;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Muhammad Faheem
 */
public class Menu extends javax.swing.JFrame {
    public static MyHashTable theHT = new MyHashTable(10);
    LoginPage LP = new LoginPage();
    FTE someFTE;
    PTE somePTE;
    public void Hashing(){
        theHT.clear();
         String fileName = LP.fileName;

        try {
            FileReader reader = new FileReader(fileName);
              BufferedReader br = new BufferedReader(reader);
            String line;

            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts[0].equals("Full-Time")){
                   someFTE = new FTE(Integer.parseInt(parts[1]),parts[3],parts[4],parts[5],parts[6],Double.parseDouble(parts[7]),Double.parseDouble(parts[11]));
                   theHT.addToTable(someFTE);
                }
                else if (parts[0].equals("Part-Time")){
                   somePTE = new PTE(Integer.parseInt(parts[1]),parts[3],parts[4],parts[5],parts[6],Double.parseDouble(parts[7]),Double.parseDouble(parts[8]),Double.parseDouble(parts[9]),Double.parseDouble(parts[10]));
                   theHT.addToTable(somePTE);
            }
        } 
            theHT.display();
            reader.close();
            br.close();
        }    
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
    }
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        File file = new File(LP.fileName);
        try{
        file.createNewFile();
        }
        catch(IOException e){           
        }
        UsernameLabel.setText((String) LP.fileName);
        jLabel3.setText("Welcome "+(String) LP.fileName+ "!");
        this.setOpacity(0.95f);
        Hashing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JPanel();
        SignOutPanel = new javax.swing.JPanel();
        SignOutLabel = new javax.swing.JLabel();
        EditPanel = new javax.swing.JPanel();
        EditLabel = new javax.swing.JLabel();
        RemovePanel = new javax.swing.JPanel();
        RemoveLabel = new javax.swing.JLabel();
        ViewPanel = new javax.swing.JPanel();
        ViewLabel = new javax.swing.JLabel();
        AddPanel = new javax.swing.JPanel();
        AddLabel = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        MenuLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ToolPanel = new javax.swing.JPanel();
        ToolLabel = new javax.swing.JLabel();
        MainRemove = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        MainRemoveLabel = new javax.swing.JLabel();
        MainAdd = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        MainAddLabel = new javax.swing.JLabel();
        MainEdit = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        MainEditLabel = new javax.swing.JLabel();
        MainView = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        MainViewLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Find = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        ExitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Information and Mangement System");
        setMaximumSize(new java.awt.Dimension(962, 541));
        setMinimumSize(new java.awt.Dimension(962, 541));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(962, 541));
        getContentPane().setLayout(null);

        MenuBar.setBackground(new java.awt.Color(0, 102, 153));
        MenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignOutPanel.setBackground(new java.awt.Color(0, 102, 153));
        SignOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignOutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignOutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignOutPanelMouseExited(evt);
            }
        });
        SignOutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignOut.png"))); // NOI18N
        SignOutPanel.add(SignOutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(SignOutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 50, 30));

        EditPanel.setBackground(new java.awt.Color(0, 102, 153));
        EditPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditPanelMouseExited(evt);
            }
        });
        EditPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit_1.png"))); // NOI18N
        EditPanel.add(EditLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(EditPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 50, 30));

        RemovePanel.setBackground(new java.awt.Color(0, 102, 153));
        RemovePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemovePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RemovePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RemovePanelMouseExited(evt);
            }
        });
        RemovePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RemoveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Remove.png"))); // NOI18N
        RemovePanel.add(RemoveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(RemovePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 50, 30));

        ViewPanel.setBackground(new java.awt.Color(0, 102, 153));
        ViewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewPanelMouseExited(evt);
            }
        });
        ViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View.png"))); // NOI18N
        ViewPanel.add(ViewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(ViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 50, 30));

        AddPanel.setBackground(new java.awt.Color(0, 102, 153));
        AddPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddPanelMouseExited(evt);
            }
        });
        AddPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        AddPanel.add(AddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(AddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 30));

        MenuPanel.setBackground(new java.awt.Color(0, 102, 153));
        MenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuPanelMouseExited(evt);
            }
        });
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu.png"))); // NOI18N
        MenuPanel.add(MenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 50, 30));

        getContentPane().add(MenuBar);
        MenuBar.setBounds(0, 0, 50, 1000);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToolPanel.setBackground(new java.awt.Color(0, 0, 0));
        ToolPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ToolPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ToolPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ToolPanelMouseExited(evt);
            }
        });
        ToolPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToolLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ToolLabel.setForeground(new java.awt.Color(255, 255, 255));
        ToolLabel.setText("Employee Management Tools");
        ToolPanel.add(ToolLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jPanel1.add(ToolPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 830, 50));

        MainRemove.setBackground(new java.awt.Color(0, 0, 0));
        MainRemove.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        MainRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainRemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MainRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MainRemoveMouseExited(evt);
            }
        });
        MainRemove.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Remove_100.png"))); // NOI18N
        MainRemove.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 12, -1, -1));

        MainRemoveLabel.setBackground(new java.awt.Color(255, 255, 255));
        MainRemoveLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        MainRemoveLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainRemoveLabel.setText("Remove Employee");
        MainRemove.add(MainRemoveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));

        jPanel1.add(MainRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, 180));

        MainAdd.setBackground(new java.awt.Color(0, 0, 0));
        MainAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        MainAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MainAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MainAddMouseExited(evt);
            }
        });
        MainAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add_100.png"))); // NOI18N
        MainAdd.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 12, -1, -1));

        MainAddLabel.setBackground(new java.awt.Color(255, 255, 255));
        MainAddLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        MainAddLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainAddLabel.setText("Add Employee");
        MainAdd.add(MainAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, -1));

        jPanel1.add(MainAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 180));

        MainEdit.setBackground(new java.awt.Color(0, 0, 0));
        MainEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        MainEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MainEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MainEditMouseExited(evt);
            }
        });
        MainEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit_100.png"))); // NOI18N
        MainEdit.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 12, -1, -1));

        MainEditLabel.setBackground(new java.awt.Color(255, 255, 255));
        MainEditLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        MainEditLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainEditLabel.setText("Edit Employee");
        MainEdit.add(MainEditLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, -1));

        jPanel1.add(MainEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 180, 180));

        MainView.setBackground(new java.awt.Color(0, 0, 0));
        MainView.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        MainView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainViewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MainViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MainViewMouseExited(evt);
            }
        });
        MainView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view_100.png"))); // NOI18N
        MainView.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 12, -1, -1));

        MainViewLabel.setBackground(new java.awt.Color(255, 255, 255));
        MainViewLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        MainViewLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainViewLabel.setText("Display System");
        MainView.add(MainViewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, -1));

        jPanel1.add(MainView, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 180, 180));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 230, 920, 500);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel3.setText("Welcome Username!");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 30, 490, 64);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover.png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(570, 10, 270, 180);

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setText("Employee Management System");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(80, 100, 238, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 50, 940, 180);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(100, 40, 210, 10);

        Find.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Find.setForeground(new java.awt.Color(255, 153, 0));
        Find.setBorder(null);
        Find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FindKeyPressed(evt);
            }
        });
        jPanel3.add(Find);
        Find.setBounds(100, 10, 210, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(60, 10, 30, 30);

        UsernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Icon.png"))); // NOI18N
        UsernameLabel.setText("Username");
        jPanel3.add(UsernameLabel);
        UsernameLabel.setBounds(820, 0, 100, 40);

        ExitPanel.setBackground(new java.awt.Color(255, 255, 255));
        ExitPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ExitPanel.setMaximumSize(new java.awt.Dimension(32, 32));
        ExitPanel.setMinimumSize(new java.awt.Dimension(32, 32));
        ExitPanel.setPreferredSize(new java.awt.Dimension(32, 32));
        ExitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitPanelMouseExited(evt);
            }
        });
        ExitPanel.setLayout(new java.awt.GridLayout(1, 0));

        ExitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit2.png"))); // NOI18N
        ExitPanel.add(ExitLabel);

        jPanel3.add(ExitPanel);
        ExitPanel.setBounds(930, 0, 32, 32);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 980, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int xMouse, yMouse;
    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y= evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse); 
    }//GEN-LAST:event_jPanel3MouseDragged

    private void MenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_MenuPanelMouseClicked

    private void MenuPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPanelMouseEntered
        MenuPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_MenuPanelMouseEntered

    private void MenuPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPanelMouseExited
        // TODO add your handling code here:
        MenuPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_MenuPanelMouseExited

    private void AddPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AddEmployee().setVisible(true);        
    }//GEN-LAST:event_AddPanelMouseClicked

    private void AddPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseEntered
        // TODO add your handling code here:
        AddPanel.setBackground(new Color(255,153,0));

    }//GEN-LAST:event_AddPanelMouseEntered

    private void AddPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseExited
        // TODO add your handling code here:
        AddPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_AddPanelMouseExited

    private void RemovePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemovePanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new RemoveEmployee().setVisible(true);
    }//GEN-LAST:event_RemovePanelMouseClicked

    private void RemovePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemovePanelMouseEntered
        // TODO add your handling code here:
       RemovePanel.setBackground(new Color(255,153,0));

    }//GEN-LAST:event_RemovePanelMouseEntered

    private void RemovePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemovePanelMouseExited
        // TODO add your handling code here:
       RemovePanel.setBackground(new Color(0,102,153));

    }//GEN-LAST:event_RemovePanelMouseExited

    private void EditPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new EditEmployee().setVisible(true);
    }//GEN-LAST:event_EditPanelMouseClicked

    private void EditPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPanelMouseEntered
        // TODO add your handling code here:
       EditPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_EditPanelMouseEntered

    private void EditPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPanelMouseExited
        // TODO add your handling code here:
       EditPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_EditPanelMouseExited

    private void ViewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPanelMouseClicked
        this.dispose();
        new DisplaySystem().setVisible(true);        
    }//GEN-LAST:event_ViewPanelMouseClicked

    private void ViewPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPanelMouseEntered
        // TODO add your handling code here:
       ViewPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_ViewPanelMouseEntered

    private void ViewPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPanelMouseExited
       ViewPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_ViewPanelMouseExited

    private void SignOutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutPanelMouseClicked
       new LoginPage().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_SignOutPanelMouseClicked

    private void SignOutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutPanelMouseEntered
       SignOutPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_SignOutPanelMouseEntered

    private void SignOutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutPanelMouseExited
       SignOutPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_SignOutPanelMouseExited

    private void ToolPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolPanelMouseEntered
        ToolLabel.setForeground(Color.WHITE);
        ToolPanel.setBackground(new Color(255,153,0));
        ToolPanel.setBorder(new LineBorder(new Color(255,153,0),1,true));
    }//GEN-LAST:event_ToolPanelMouseEntered

    private void ToolPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolPanelMouseExited
        ToolLabel.setForeground(Color.WHITE);
        ToolPanel.setBackground(Color.BLACK);
        ToolPanel.setBorder(new LineBorder(Color.WHITE,1,true));
       }//GEN-LAST:event_ToolPanelMouseExited

    private void MainAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainAddMouseClicked
        this.dispose();
        new AddEmployee().setVisible(true);
    }//GEN-LAST:event_MainAddMouseClicked

    private void MainAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainAddMouseEntered
        MainAddLabel.setForeground(Color.WHITE);
        MainAdd.setBackground(new Color(255,153,0));
        MainAdd.setBorder(new LineBorder(new Color(255,153,0),1,true));
    }//GEN-LAST:event_MainAddMouseEntered

    private void MainAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainAddMouseExited
        MainAddLabel.setForeground(Color.WHITE);
        MainAdd.setBackground(Color.BLACK);
        MainAdd.setBorder(new LineBorder(Color.WHITE,1,true));
    }//GEN-LAST:event_MainAddMouseExited

    private void MainRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainRemoveMouseClicked
        this.dispose();
        new RemoveEmployee().setVisible(true);
    }//GEN-LAST:event_MainRemoveMouseClicked

    private void MainRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainRemoveMouseEntered
        MainRemoveLabel.setForeground(Color.WHITE);
        MainRemove.setBackground(new Color(255,153,0));
        MainRemove.setBorder(new LineBorder(new Color(255,153,0),1,true));    }//GEN-LAST:event_MainRemoveMouseEntered

    private void MainRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainRemoveMouseExited
        MainRemoveLabel.setForeground(Color.WHITE);
        MainRemove.setBackground(Color.BLACK);
        MainRemove.setBorder(new LineBorder(Color.WHITE,1,true));
    }//GEN-LAST:event_MainRemoveMouseExited

    private void MainEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainEditMouseClicked
        this.dispose();
        new EditEmployee().setVisible(true);
    }//GEN-LAST:event_MainEditMouseClicked

    private void MainEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainEditMouseEntered
        MainEditLabel.setForeground(Color.WHITE);
        MainEdit.setBackground(new Color(255,153,0));
        MainEdit.setBorder(new LineBorder(new Color(255,153,0),1,true));     
    }//GEN-LAST:event_MainEditMouseEntered

    private void MainEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainEditMouseExited
        MainEditLabel.setForeground(Color.WHITE);
        MainEdit.setBackground(Color.BLACK);
        MainEdit.setBorder(new LineBorder(Color.WHITE,1,true));    }//GEN-LAST:event_MainEditMouseExited

    private void MainViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainViewMouseClicked
        this.dispose();
        new DisplaySystem().setVisible(true);
    }//GEN-LAST:event_MainViewMouseClicked

    private void MainViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainViewMouseEntered
        MainViewLabel.setForeground(Color.WHITE);
        MainView.setBackground(new Color(255,153,0));
        MainView.setBorder(new LineBorder(new Color(255,153,0),1,true));
    }//GEN-LAST:event_MainViewMouseEntered

    private void MainViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainViewMouseExited
        MainViewLabel.setForeground(Color.WHITE);
        MainView.setBackground(Color.BLACK);
        MainView.setBorder(new LineBorder(Color.WHITE,1,true));                                       
     }//GEN-LAST:event_MainViewMouseExited

    private void ExitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitPanelMouseClicked

    private void ExitPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseEntered
        ExitLabel.setForeground(Color.WHITE);
        ExitPanel.setBackground(new Color(255, 255, 255));
        ExitPanel.setBorder(new LineBorder(new Color(255, 153, 0), 1, true));
    }//GEN-LAST:event_ExitPanelMouseEntered

    private void ExitPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseExited
        ExitLabel.setForeground(new Color(255, 153, 0));
        ExitPanel.setBackground(new Color(0, 102, 153));
        ExitPanel.setBorder(new LineBorder(Color.WHITE, 0, true));
    }//GEN-LAST:event_ExitPanelMouseExited

    private void FindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FindKeyPressed
 DisplaySystem DS = new DisplaySystem();
          if (evt.getKeyCode()==KeyEvent.VK_ENTER){
          DS.Search(Find.getText().trim());
         }    }//GEN-LAST:event_FindKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLabel;
    private javax.swing.JPanel AddPanel;
    private javax.swing.JLabel EditLabel;
    private javax.swing.JPanel EditPanel;
    private javax.swing.JLabel ExitLabel;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JTextField Find;
    private javax.swing.JPanel MainAdd;
    private javax.swing.JLabel MainAddLabel;
    private javax.swing.JPanel MainEdit;
    private javax.swing.JLabel MainEditLabel;
    private javax.swing.JPanel MainRemove;
    private javax.swing.JLabel MainRemoveLabel;
    private javax.swing.JPanel MainView;
    private javax.swing.JLabel MainViewLabel;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JLabel RemoveLabel;
    private javax.swing.JPanel RemovePanel;
    private javax.swing.JLabel SignOutLabel;
    private javax.swing.JPanel SignOutPanel;
    private javax.swing.JLabel ToolLabel;
    private javax.swing.JPanel ToolPanel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel ViewLabel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
