/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InheritancePackage;

import static InheritancePackage.Menu.theHT;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Muhammad Faheem
 */
public class RemoveEmployee extends javax.swing.JFrame {
    Menu menu = new Menu();
    public MyHashTable theHT = Menu.theHT;
    LoginPage LP = new LoginPage();
    boolean found = false;
    /**
     * Creates new form RemoveEmployee
     * @param 
     */

    public void RemoveEmployee(String s){
        try{
        File inputFile = new File(LP.fileName);
        File tempFile = new File("EmployeeTemp.txt");

        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));

        String lineToRemove = s;
        String currentLine;
        while ((currentLine = reader.readLine()) != null) {
            String[] parts = currentLine.split(",");
              
            if (parts[1].equals(lineToRemove)) {
                continue;
            }
            
            writer.write(currentLine + "\n");
        }
        writer.close();
        reader.close();
        inputFile.delete();
        tempFile.renameTo(inputFile);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); ;

        }
    }
    public void SearchForRemove(String s){

         String fileName = LP.fileName;

       try {
            FileReader reader = new FileReader(fileName);
            BufferedReader br = new BufferedReader(reader); 

            String line;

            while ((line = br.readLine()) != null) {
               String[] parts = line.split(",");
                if (parts[1].equals(s)){
                    found =  true;
            }
            }
        reader.close();
        br.close();
       }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage()); ;
        }
    }    
    public RemoveEmployee() {
        initComponents();
        UsernameLabel.setText((String) LP.fileName);
        this.setOpacity(0.95f);
        menu.Hashing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JPanel();
        SignOutPanel = new javax.swing.JPanel();
        SignOutLabel = new javax.swing.JLabel();
        EditPanel = new javax.swing.JPanel();
        EditLabel = new javax.swing.JLabel();
        RemovePanel = new javax.swing.JPanel();
        RemoveLabel = new javax.swing.JLabel();
        ViewPanel = new javax.swing.JPanel();
        ViewLabel = new javax.swing.JLabel();
        AddPanel = new javax.swing.JPanel();
        AddLabel = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        MenuLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ToolPanel = new javax.swing.JPanel();
        ToolLabel = new javax.swing.JLabel();
        eN = new javax.swing.JLabel();
        RemoveIEN = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Remove = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        GarbageLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Find = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        ExitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Information and Mangement System");
        setMinimumSize(new java.awt.Dimension(640, 446));
        setUndecorated(true);
        getContentPane().setLayout(null);

        MenuBar.setBackground(new java.awt.Color(0, 102, 153));
        MenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignOutPanel.setBackground(new java.awt.Color(0, 102, 153));
        SignOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignOutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignOutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignOutPanelMouseExited(evt);
            }
        });
        SignOutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignOut.png"))); // NOI18N
        SignOutPanel.add(SignOutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(SignOutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 50, 30));

        EditPanel.setBackground(new java.awt.Color(0, 102, 153));
        EditPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditPanelMouseExited(evt);
            }
        });
        EditPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit_1.png"))); // NOI18N
        EditPanel.add(EditLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(EditPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 50, 30));

        RemovePanel.setBackground(new java.awt.Color(0, 102, 153));
        RemovePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemovePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RemovePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RemovePanelMouseExited(evt);
            }
        });
        RemovePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RemoveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Remove.png"))); // NOI18N
        RemovePanel.add(RemoveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(RemovePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 50, 30));

        ViewPanel.setBackground(new java.awt.Color(0, 102, 153));
        ViewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewPanelMouseExited(evt);
            }
        });
        ViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View.png"))); // NOI18N
        ViewPanel.add(ViewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(ViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 50, 30));

        AddPanel.setBackground(new java.awt.Color(0, 102, 153));
        AddPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddPanelMouseExited(evt);
            }
        });
        AddPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        AddPanel.add(AddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(AddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 30));

        MenuPanel.setBackground(new java.awt.Color(0, 102, 153));
        MenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuPanelMouseExited(evt);
            }
        });
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu.png"))); // NOI18N
        MenuPanel.add(MenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        MenuBar.add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 50, 30));

        getContentPane().add(MenuBar);
        MenuBar.setBounds(0, 0, 50, 1000);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToolPanel.setBackground(new java.awt.Color(0, 0, 0));
        ToolPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ToolPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ToolPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ToolPanelMouseExited(evt);
            }
        });
        ToolPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToolLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ToolLabel.setForeground(new java.awt.Color(255, 255, 255));
        ToolLabel.setText("Remove Employee to the System");
        ToolPanel.add(ToolLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jPanel1.add(ToolPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 50));

        eN.setBackground(new java.awt.Color(255, 255, 255));
        eN.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        eN.setForeground(new java.awt.Color(51, 52, 54));
        eN.setText("Employee Number");
        jPanel1.add(eN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        RemoveIEN.setBackground(new java.awt.Color(0, 0, 0));
        RemoveIEN.setBorder(null);
        RemoveIEN.setForeground(new java.awt.Color(255, 153, 0));
        RemoveIEN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        RemoveIEN.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RemoveIEN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RemoveIENFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RemoveIENFocusLost(evt);
            }
        });
        RemoveIEN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RemoveIENKeyPressed(evt);
            }
        });
        jPanel1.add(RemoveIEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 560, 20));

        jSeparator2.setMaximumSize(null);
        jSeparator2.setMinimumSize(null);
        jSeparator2.setPreferredSize(null);
        jSeparator2.setRequestFocusEnabled(false);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 560, -1));

        Remove.setBackground(new java.awt.Color(0, 0, 0));
        Remove.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Remove.setFocusTraversalPolicyProvider(true);
        Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RemoveMouseExited(evt);
            }
        });
        Remove.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remove_icon.png"))); // NOI18N
        Remove.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        GarbageLabel.setBackground(new java.awt.Color(255, 255, 255));
        GarbageLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        GarbageLabel.setForeground(new java.awt.Color(255, 255, 255));
        GarbageLabel.setText("Remove");
        Remove.add(GarbageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, -1));

        jPanel1.add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 80));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 50, 920, 640);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(100, 40, 210, 10);

        Find.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Find.setForeground(new java.awt.Color(255, 153, 0));
        Find.setBorder(null);
        Find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FindKeyPressed(evt);
            }
        });
        jPanel3.add(Find);
        Find.setBounds(100, 10, 210, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(60, 10, 32, 30);

        UsernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Icon.png"))); // NOI18N
        UsernameLabel.setText("Username");
        jPanel3.add(UsernameLabel);
        UsernameLabel.setBounds(460, 0, 100, 40);

        ExitPanel.setBackground(new java.awt.Color(255, 255, 255));
        ExitPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ExitPanel.setMaximumSize(new java.awt.Dimension(32, 32));
        ExitPanel.setMinimumSize(new java.awt.Dimension(32, 32));
        ExitPanel.setPreferredSize(new java.awt.Dimension(32, 32));
        ExitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitPanelMouseExited(evt);
            }
        });
        ExitPanel.setLayout(new java.awt.GridLayout(1, 0));

        ExitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit2.png"))); // NOI18N
        ExitPanel.add(ExitLabel);

        jPanel3.add(ExitPanel);
        ExitPanel.setBounds(590, 0, 32, 32);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 980, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int xMouse, yMouse;
    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y= evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse); 
    }//GEN-LAST:event_jPanel3MouseDragged

    private void MenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_MenuPanelMouseClicked

    private void MenuPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPanelMouseEntered
        MenuPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_MenuPanelMouseEntered

    private void MenuPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPanelMouseExited
        // TODO add your handling code here:
        MenuPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_MenuPanelMouseExited

    private void AddPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AddEmployee().setVisible(true);        
    }//GEN-LAST:event_AddPanelMouseClicked

    private void AddPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseEntered
        // TODO add your handling code here:
        AddPanel.setBackground(new Color(255,153,0));

    }//GEN-LAST:event_AddPanelMouseEntered

    private void AddPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseExited
        // TODO add your handling code here:
        AddPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_AddPanelMouseExited

    private void RemovePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemovePanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new RemoveEmployee().setVisible(true);
    }//GEN-LAST:event_RemovePanelMouseClicked

    private void RemovePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemovePanelMouseEntered
        // TODO add your handling code here:
       RemovePanel.setBackground(new Color(255,153,0));

    }//GEN-LAST:event_RemovePanelMouseEntered

    private void RemovePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemovePanelMouseExited
        // TODO add your handling code here:
       RemovePanel.setBackground(new Color(0,102,153));

    }//GEN-LAST:event_RemovePanelMouseExited

    private void EditPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new EditEmployee().setVisible(true);
    }//GEN-LAST:event_EditPanelMouseClicked

    private void EditPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPanelMouseEntered
        // TODO add your handling code here:
       EditPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_EditPanelMouseEntered

    private void EditPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPanelMouseExited
        // TODO add your handling code here:
       EditPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_EditPanelMouseExited

    private void ViewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPanelMouseClicked
        this.dispose();
        new DisplaySystem().setVisible(true);        
    }//GEN-LAST:event_ViewPanelMouseClicked

    private void ViewPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPanelMouseEntered
        // TODO add your handling code here:
       ViewPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_ViewPanelMouseEntered

    private void ViewPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPanelMouseExited
       ViewPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_ViewPanelMouseExited

    private void SignOutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutPanelMouseClicked
       new LoginPage().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_SignOutPanelMouseClicked

    private void SignOutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutPanelMouseEntered
       SignOutPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_SignOutPanelMouseEntered

    private void SignOutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutPanelMouseExited
       SignOutPanel.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_SignOutPanelMouseExited

    private void ToolPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolPanelMouseEntered
        ToolLabel.setForeground(Color.WHITE);
        ToolPanel.setBackground(new Color(255,153,0));
        ToolPanel.setBorder(new LineBorder(new Color(255,153,0),1,true));
    }//GEN-LAST:event_ToolPanelMouseEntered

    private void ToolPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolPanelMouseExited
        ToolLabel.setForeground(Color.WHITE);
        ToolPanel.setBackground(Color.BLACK);
        ToolPanel.setBorder(new LineBorder(Color.WHITE,1,true));
       }//GEN-LAST:event_ToolPanelMouseExited

    private void ExitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitPanelMouseClicked

    private void ExitPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseEntered
        ExitLabel.setForeground(Color.WHITE);
        ExitPanel.setBackground(new Color(255, 255, 255));
        ExitPanel.setBorder(new LineBorder(new Color(255, 153, 0), 1, true));
    }//GEN-LAST:event_ExitPanelMouseEntered

    private void ExitPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseExited
        ExitLabel.setForeground(new Color(255, 153, 0));
        ExitPanel.setBackground(new Color(0, 102, 153));
        ExitPanel.setBorder(new LineBorder(Color.WHITE, 0, true));
    }//GEN-LAST:event_ExitPanelMouseExited

    private void RemoveIENFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RemoveIENFocusGained
        // TODO add your handling code here
        jSeparator2.setBackground(Color.yellow);
        eN.setForeground(new Color(53,113,177));
    }//GEN-LAST:event_RemoveIENFocusGained

    private void RemoveIENFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RemoveIENFocusLost
        eN.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_RemoveIENFocusLost

    private void RemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseExited
        // TODO add your handling code here:
        GarbageLabel.setForeground(Color.white);
        Remove.setBackground(Color.BLACK);
        Remove.setBorder(new LineBorder(Color.WHITE,1,true));
    }//GEN-LAST:event_RemoveMouseExited

    private void RemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseEntered
        // TODO add your handling code here:
        GarbageLabel.setForeground(Color.WHITE);
        Remove.setBackground(new Color(255,153,0));
        Remove.setBorder(new LineBorder(new Color(255,153,0),1,true));
    }//GEN-LAST:event_RemoveMouseEntered

    private void RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseClicked
        // TODO add your handling code here:
        SearchForRemove(RemoveIEN.getText().trim());
        if (RemoveIEN.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "FILL IN ALL FIELDS!");
        } else if (found == true) {
            RemoveEmployee(RemoveIEN.getText().trim());
            theHT.removeFromTable(Integer.parseInt(RemoveIEN.getText().trim()));
            JOptionPane.showMessageDialog(null, "Removed Employee");
            theHT.display();
            RemoveIEN.setText("");
            found = false;
        } else {
            JOptionPane.showMessageDialog(null, "Employee number not in database!");
        }
       
    }//GEN-LAST:event_RemoveMouseClicked

    private void FindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FindKeyPressed
 DisplaySystem DS = new DisplaySystem();
          if (evt.getKeyCode()==KeyEvent.VK_ENTER){
          DS.Search(Find.getText().trim());
         }    }//GEN-LAST:event_FindKeyPressed

    private void RemoveIENKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RemoveIENKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        SearchForRemove(RemoveIEN.getText().trim());
        if (RemoveIEN.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "FILL IN ALL FIELDS!");
        } else if (found == true) {
            RemoveEmployee(RemoveIEN.getText().trim());
            theHT.removeFromTable(Integer.parseInt(RemoveIEN.getText().trim()));
            JOptionPane.showMessageDialog(null, "Removed Employee");
            theHT.display();
            RemoveIEN.setText("");
            found = false;
        } else {
            JOptionPane.showMessageDialog(null, "Employee number not in database!");
        }
        }
    }//GEN-LAST:event_RemoveIENKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLabel;
    private javax.swing.JPanel AddPanel;
    private javax.swing.JLabel EditLabel;
    private javax.swing.JPanel EditPanel;
    private javax.swing.JLabel ExitLabel;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JTextField Find;
    private javax.swing.JLabel GarbageLabel;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel Remove;
    private javax.swing.JFormattedTextField RemoveIEN;
    private javax.swing.JLabel RemoveLabel;
    private javax.swing.JPanel RemovePanel;
    private javax.swing.JLabel SignOutLabel;
    private javax.swing.JPanel SignOutPanel;
    private javax.swing.JLabel ToolLabel;
    private javax.swing.JPanel ToolPanel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel ViewLabel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JLabel eN;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
